package tests

import "github.com/maxonrow/maxonrow-go/utils"

func makeMultisigTxsNFTs() []*testCase {

	// Group addresses:
	// You can generate group address via `mxwcli` command. ex.
	// `mxwcli keys multisig-address "mxw1ydvzacxj0ws9jadxkmdzamc897jmln5dd90fzh" 1`
	tKeys["nft-grp-addr-1"] = &keyInfo{
		utils.MustGetAccAddressFromBech32("mxw10hu6zlsh4es6fnr3t6p884zzpdfnxfezau5khr"), nil, nil, "mxw10hu6zlsh4es6fnr3t6p884zzpdfnxfezau5khr",
	}
	// `mxwcli keys multisig-address "mxw1ydvzacxj0ws9jadxkmdzamc897jmln5dd90fzh" 2`
	tKeys["nft-grp-addr-2"] = &keyInfo{
		utils.MustGetAccAddressFromBech32("mxw1cq77f9vtl7ax9aant9sdjvyetsd5v4kryaxpwu"), nil, nil, "mxw1cq77f9vtl7ax9aant9sdjvyetsd5v4kryaxpwu",
	}
	// `mxwcli keys multisig-address "mxw1ydvzacxj0ws9jadxkmdzamc897jmln5dd90fzh" 3`
	tKeys["nft-grp-addr-3"] = &keyInfo{
		utils.MustGetAccAddressFromBech32("mxw1pamcuxj696gncrg5e3kg29k2e0gk4jc40uluht"), nil, nil, "mxw1pamcuxj696gncrg5e3kg29k2e0gk4jc40uluht",
	}

	// `mxwcli keys multisig-address "mxw1ydvzacxj0ws9jadxkmdzamc897jmln5dd90fzh" 4`
	tKeys["nft-grp-addr-4"] = &keyInfo{
		utils.MustGetAccAddressFromBech32("mxw1ukuenztvcqsytv0axrqcvrzx6f2cqmtzk7ruz3"), nil, nil, "mxw1ukuenztvcqsytv0axrqcvrzx6f2cqmtzk7ruz3",
	}

	// not exist account
	// `mxwcli keys multisig-address "mxw1ydvzacxj0ws9jadxkmdzamc897jmln5dd90fzh" 5`
	tKeys["nft-grp-addr-5"] = &keyInfo{
		utils.MustGetAccAddressFromBech32("mxw1300ry2de2uyxthzxwz2hymnahxmrw64h80p2gn"), nil, nil, "mxw1300ry2de2uyxthzxwz2hymnahxmrw64h80p2gn",
	}

	internalTx2x_createToken1 := &testCase{"nonFungibleToken", false, false, "CREATE non fungible token [TNFT-PUBLIC-FALSE-01] - Happy Path.  commit", "multisig-acc-nft-1", "100000000cin", 0, NonFungibleTokenInfo{"create", "10000000", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-01", "nft-grp-addr-1", "", "token metadata", "", "item-properties", "item-metadata", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx2x_createToken1", nil}
	internalTx2x_mintItem1 := &testCase{"nonFungibleToken", false, false, "MINT non fungible item [Item-PUBLIC-FALSE-01] - Happy path.  commit", "multisig-acc-nft-1", "100000000cin", 0, NonFungibleTokenInfo{"mint-item", "10000000", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-01", "nft-grp-addr-1", "nft-mostafa", "token metadata", "Item-PUBLIC-FALSE-01", "item-properties", "item-metadata", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx2x_mintItem1", nil}
	internalTx2x_burnItem1 := &testCase{"nonFungibleToken", false, false, "BURN non fungible item [Item-PUBLIC-FALSE-01] - Happy path.  commit", "multisig-acc-nft-1", "100000000cin", 0, NonFungibleTokenInfo{"burn-item", "", "", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-01", "nft-grp-addr-1", "", "token metadata", "Item-PUBLIC-FALSE-01", "item-properties", "item-metadata", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx2x_burnItem1", nil}
	internalTx2x_transferTokenOwnership1 := &testCase{"nonFungibleToken", false, false, "TRANSFER non fungible token ownership [TNFT-PUBLIC-FALSE-01] - Happy path. commit", "multisig-acc-nft-1", "100000000cin", 0, NonFungibleTokenInfo{"transfer-token-ownership", "", "", "", "TNFT-PUBLIC-FALSE-01", "nft-grp-addr-1", "nft-grp-addr-3", "token metadata", "", "", "", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx2x_transferTokenOwnership1", nil}
	internalTx2x_acceptTokenOwnership1 := &testCase{"nonFungibleToken", false, false, "ACCEPT non fungible token ownership [TNFT-PUBLIC-FALSE-01] - Happy path. commit", "multisig-acc-nft-2", "100000000cin", 0, NonFungibleTokenInfo{"accept-token-ownership", "", "", "", "TNFT-PUBLIC-FALSE-01", "", "nft-grp-addr-3", "token metadata", "", "", "", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx2x_acceptTokenOwnership1", nil}
	internalTx2x_mintItem_freeze1 := &testCase{"nonFungibleToken", false, false, "MINT non fungible item [Item-PUBLIC-FALSE-99] - Happy path.  commit", "multisig-acc-nft-1", "100000000cin", 0, NonFungibleTokenInfo{"mint-item", "10000000", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-01", "nft-grp-addr-1", "nft-mostafa", "token metadata", "Item-PUBLIC-FALSE-99", "item-properties", "item-metadata", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx2x_mintItem_freeze1", nil}

	internalTx3x_createToken1 := &testCase{"nonFungibleToken", false, false, "CREATE non fungible token [TNFT-PUBLIC-FALSE-02] - Happy Path.  commit", "multisig-acc-nft-2", "100000000cin", 0, NonFungibleTokenInfo{"create", "10000000", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-02", "nft-grp-addr-2", "", "token metadata", "", "item-properties", "item-metadata", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx3x_createToken1", nil}
	internalTx3x_mintItem1 := &testCase{"nonFungibleToken", false, false, "MINT non fungible item [Item-PUBLIC-FALSE-02] - Happy path.  commit", "multisig-acc-nft-2", "100000000cin", 0, NonFungibleTokenInfo{"mint-item", "10000000", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-02", "nft-grp-addr-2", "nft-mostafa", "token metadata", "Item-PUBLIC-FALSE-02", "item-properties", "item-metadata", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx3x_mintItem1", nil}
	internalTx3x_burnItem1 := &testCase{"nonFungibleToken", false, false, "BURN non fungible item [Item-PUBLIC-FALSE-02] - Happy path.  commit", "multisig-acc-nft-2", "100000000cin", 0, NonFungibleTokenInfo{"burn-item", "", "", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-02", "nft-grp-addr-2", "", "token metadata", "Item-PUBLIC-FALSE-02", "item-properties", "item-metadata", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx3x_burnItem1", nil}
	internalTx3x_transferTokenOwnership1 := &testCase{"nonFungibleToken", false, false, "TRANSFER non fungible token ownership [TNFT-PUBLIC-FALSE-02] - Happy path. commit", "multisig-acc-nft-2", "100000000cin", 0, NonFungibleTokenInfo{"transfer-token-ownership", "10000000", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-02", "nft-grp-addr-2", "nft-grp-addr-4", "token metadata", "", "", "", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx3x_transferTokenOwnership1", nil}
	internalTx3x_acceptTokenOwnership1 := &testCase{"nonFungibleToken", false, false, "ACCEPT non fungible token ownership [TNFT-PUBLIC-FALSE-02] - Happy path. commit", "multisig-acc-nft-2", "100000000cin", 0, NonFungibleTokenInfo{"accept-token-ownership", "10000000", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-02", "", "nft-grp-addr-4", "token metadata", "", "", "", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx3x_acceptTokenOwnership1", nil}

	// update-nft-metadata :
	internalTx3x_updateNFTMetadata_err1 := &testCase{"nonFungibleToken", true, true, "UPDATE NFT METADATA nonfungible token - Invalid metadata field length due to very long token metadata!", "multisig-acc-nft-2", "100000000cin", 0, NonFungibleTokenInfo{"update-nft-metadata", "0", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-02", "nft-grp-addr-2", "", "NFT Metadata updated here by nft-grp-addr-2 : aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAA------aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaBBBBBB----aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaCCCCCC------aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAA-DDDDDD------aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAA-PPPPPP------aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAA-QQQQQQ------aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAA-RRRRRR------aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAA-SSSSSS", "", "", "", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx3x_updateNFTMetadata_err1", nil}
	internalTx3x_updateNFTMetadata_err3 := &testCase{"nonFungibleToken", true, true, "UPDATE NFT METADATA nonfungible token - Invalid token-symbol.", "multisig-acc-nft-2", "100000000cin", 0, NonFungibleTokenInfo{"update-nft-metadata", "0", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-02-----xyz", "nft-grp-addr-2", "", "token metadata updated here by nft-grp-addr-2", "", "", "", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx3x_updateNFTMetadata_err3", nil}
	internalTx3x_updateNFTMetadata1 := &testCase{"nonFungibleToken", false, false, "UPDATE NFT METADATA nonfungible token - Happy Path.  commit", "multisig-acc-nft-2", "100000000cin", 0, NonFungibleTokenInfo{"update-nft-metadata", "0", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-02", "nft-grp-addr-2", "", "token metadata updated here by nft-grp-addr-2", "", "", "", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx3x_updateNFTMetadata1", nil}
	internalTx3x_updateNFTMetadata_Reupdate1 := &testCase{"nonFungibleToken", false, false, "Re-UPDATE NFT METADATA nonfungible token - Happy Path.  commit", "multisig-acc-nft-2", "100000000cin", 0, NonFungibleTokenInfo{"update-nft-metadata", "0", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-02", "nft-grp-addr-2", "", "token metadata updated here by nft-grp-addr-2", "", "", "", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: Re-UPDATE TOKEN METADATA nonfungible item again here, in order to test the ability of it", nil} //Re-action

	// refer NFTs: 3.
	internalTx3x_mintItem_err1 := &testCase{"nonFungibleToken", true, true, "MINT non fungible item [Item-PUBLIC-FALSE-02] - Invalid Token Symbol", "multisig-acc-nft-2", "100000000cin", 0, NonFungibleTokenInfo{"mint-item", "10000000", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-02111", "nft-grp-addr-2", "nft-mostafa", "token metadata", "Item-PUBLIC-FALSE-02", "item-properties", "item-metadata", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx3x_mintItem_err1", nil}
	internalTx3x_mintItem_err3 := &testCase{"nonFungibleToken", true, true, "MINT non fungible item [Item-PUBLIC-FALSE-02] - Re-mint Not allowed due to Token item id is in used.", "multisig-acc-nft-2", "100000000cin", 0, NonFungibleTokenInfo{"mint-item", "10000000", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-02", "nft-grp-addr-2", "nft-mostafa", "token metadata", "Item-PUBLIC-FALSE-02", "item-properties", "item-metadata", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx3x_mintItem_err3", nil}
	internalTx3x_mintItem_err4 := &testCase{"nonFungibleToken", true, true, "MINT non fungible item [Item-PUBLIC-FALSE-02] - Re-mint Not allowed due to MINT limit exceeded.", "multisig-acc-nft-2", "100000000cin", 0, NonFungibleTokenInfo{"mint-item", "10000000", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-02", "nft-grp-addr-2", "nft-mostafa", "token metadata", "Item-PUBLIC-FALSE-02", "item-properties", "item-metadata", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx3x_mintItem_err4", nil}
	internalTx3x_mintItem_Remint1 := &testCase{"nonFungibleToken", false, false, "MINT non fungible item [Item-PUBLIC-FALSE-02yy] - Re-mint Not allowed due to MINT limit not exceed.  commit", "multisig-acc-nft-2", "100000000cin", 0, NonFungibleTokenInfo{"mint-item", "10000000", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-02", "nft-grp-addr-2", "nft-mostafa", "token metadata", "Item-PUBLIC-FALSE-02yy", "item-properties", "item-metadata", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx3x_mintItem1", nil}

	// refer NFTs: 6.
	internalTx3x_burnItem_err1 := &testCase{"nonFungibleToken", true, true, "BURN non fungible item [Item-PUBLIC-FALSE-02] - Invalid Token Symbol", "multisig-acc-nft-2", "100000000cin", 0, NonFungibleTokenInfo{"burn-item", "", "", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-029999", "nft-grp-addr-2", "", "token metadata", "Item-PUBLIC-FALSE-02", "item-properties", "item-metadata", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx3x_burnItem_err1", nil}
	internalTx3x_burnItem_err3 := &testCase{"nonFungibleToken", true, true, "BURN non fungible item [Item-PUBLIC-FALSE-02] - Invalid Item ID", "multisig-acc-nft-2", "100000000cin", 0, NonFungibleTokenInfo{"burn-item", "", "", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-02", "nft-grp-addr-2", "", "token metadata", "Item-PUBLIC-FALSE-02111123", "item-properties", "item-metadata", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx3x_burnItem_err3", nil}

	// refer NFTs: 7.
	internalTx3x_transferTokenOwnership_err1 := &testCase{"nonFungibleToken", true, true, "TRANSFER non fungible token ownership [TNFT-PUBLIC-FALSE-02] - Invalid token as yet to approved", "multisig-acc-nft-2", "100000000cin", 0, NonFungibleTokenInfo{"transfer-token-ownership", "10000000", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-02111111123", "nft-grp-addr-2", "nft-grp-addr-4", "token metadata", "", "", "", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx3x_transferTokenOwnership_err1", nil}
	internalTx3x_transferTokenOwnership_err3 := &testCase{"nonFungibleToken", true, true, "Re-TRANSFER non fungible token ownership [TNFT-PUBLIC-FALSE-02] - Error due to Invalid TransferTokenOwnershipFlag", "multisig-acc-nft-2", "100000000cin", 0, NonFungibleTokenInfo{"transfer-token-ownership", "10000000", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-02", "nft-grp-addr-2", "nft-grp-addr-4", "token metadata", "", "", "", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx3x_transferTokenOwnership_err3", nil}

	// refer NFTs: 9.
	internalTx3x_acceptTokenOwnership_err1 := &testCase{"nonFungibleToken", true, true, "ACCEPT non fungible token ownership [TNFT-PUBLIC-FALSE-02] - Invalid token as yet to approved", "multisig-acc-nft-2", "100000000cin", 0, NonFungibleTokenInfo{"accept-token-ownership", "10000000", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-02777777777123", "", "nft-grp-addr-4", "token metadata", "", "", "", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx3x_acceptTokenOwnership_err1", nil}
	internalTx3x_acceptTokenOwnership_err3 := &testCase{"nonFungibleToken", true, true, "ACCEPT non fungible token ownership [TNFT-PUBLIC-FALSE-02] - Invalid token due to IsTokenOwnershipTransferrable == FALSE", "multisig-acc-nft-2", "100000000cin", 0, NonFungibleTokenInfo{"accept-token-ownership", "10000000", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-02", "", "nft-grp-addr-4", "token metadata", "", "", "", false, false, false, false, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: internalTx3x_acceptTokenOwnership_err3", nil}

	tcs := []*testCase{

		//create MultiSig Account1 : {"multisig-acc-nft-1"}, owner=="multisig-acc-nft-1"
		{"multiSig", false, false, "Create MultiSig Account1 - Happy Path - commit ", "multisig-acc-nft-1", "800400000cin", 0, MultisigInfo{"create", "multisig-acc-nft-1", "", 1, []string{"multisig-acc-nft-1"}, "", 0, nil}, "MEMO : Create MultiSig Account - Happy Path", nil},
		//create MultiSig Account2 : {"multisig-acc-nft-2", "multisig-acc-nft-3"}, owner=="multisig-acc-nft-1"
		{"multiSig", false, false, "Create MultiSig Account2- Happy Path - commit  ", "multisig-acc-nft-1", "800400000cin", 0, MultisigInfo{"create", "multisig-acc-nft-1", "", 2, []string{"multisig-acc-nft-2", "multisig-acc-nft-3"}, "", 0, nil}, "MEMO : Create MultiSig Account - Happy Path", nil},
		//create MultiSig Account3 : {"multisig-acc-nft-2", "multisig-acc-nft-3", "multisig-acc-nft-4"}, owner=="multisig-acc-nft-1"
		{"multiSig", false, false, "Create MultiSig Account3 - Happy Path - commit ", "multisig-acc-nft-1", "800400000cin", 0, MultisigInfo{"create", "multisig-acc-nft-1", "", 2, []string{"multisig-acc-nft-2", "multisig-acc-nft-3", "multisig-acc-nft-4"}, "", 0, nil}, "MEMO : Create MultiSig Account - Happy Path", nil},
		{"multiSig", true, true, "Create MultiSig Account - nonkyc                ", "multisig-acc-nft-1", "800400000cin", 0, MultisigInfo{"create", "multisig-acc-nft-1", "", 2, []string{"multisig-acc-nft-1", "multisig-nokyc"}, "", 0, nil}, "", nil},

		//create MultiSig Account4 : {"multisig-acc-nft-2", "multisig-acc-nft-3", "multisig-acc-nft-4"}, owner=="multisig-acc-nft-1"
		{"multiSig", false, false, "Create MultiSig Account4 - Happy Path - commit ", "multisig-acc-nft-1", "800400000cin", 0, MultisigInfo{"create", "multisig-acc-nft-1", "", 3, []string{"multisig-acc-nft-2", "multisig-acc-nft-3", "multisig-acc-nft-4"}, "", 0, nil}, "MEMO : Create MultiSig Account - Happy Path", nil},

		//1. module : bank_test
		{"bank", false, false, "top-up Multisig Group-address1 - commit", "multisig-acc-nft-1", "800400000cin", 0, bankInfo{"multisig-acc-nft-1", "nft-grp-addr-1", "10000000000cin"}, "MEMO : top-up account", nil},
		{"bank", false, false, "top-up Multisig Group-address2 - commit", "multisig-acc-nft-2", "800400000cin", 0, bankInfo{"multisig-acc-nft-2", "nft-grp-addr-2", "10000000000cin"}, "MEMO : top-up account", nil},
		{"bank", false, false, "top-up Multisig Group-address3 - commit", "multisig-acc-nft-3", "800400000cin", 0, bankInfo{"multisig-acc-nft-3", "nft-grp-addr-3", "10000000000cin"}, "MEMO : top-up account", nil},
		{"bank", false, false, "top-up Multisig Group-address4 - commit", "multisig-acc-nft-4", "800400000cin", 0, bankInfo{"multisig-acc-nft-4", "nft-grp-addr-4", "10000000000cin"}, "MEMO : top-up account", nil},

		//2. refer module : kyc_test
		//case : whitelisted this address 'nft-mostafa'

		//3. refer module : maintenance_test
		//case-1 : add nft-mostafa as nonfungible authorised address (add, CastAction)
		//case-2 : add nft-carlo as nonfungible issuer address (add, CastAction)
		//case-3 : add nft-jeansoon as nonfungible provider address (add, CastAction)
		//case-4 : (NFTs) add nameservice fee collector with maintenance. (nft-mostafa is whitelisted.)

		//4. refer module : fee_test
		//case : assign zero-fee to nft-mostafa commit

		// ============================================case-1.0 :  with ONE signer - HAPPY-PATH
		//create-token
		{"multiSig", false, false, "[case-1.0] Create MultiSig Tx for NFTs [Create-token] - submit counter+ - Happy Path - wait-5-seconds.", "multisig-acc-nft-1", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-1", 0, internalTx2x_createToken1}, "MEMO : xxxxx", nil}, // nx "sequence":

		//Multisig Process : delete tx - before start 'Sign MultiSig Tx'
		{"multiSig", true, true, "[case-1.0] Delete MultiSig Tx - Error, due to Group address invalid.													", "multisig-acc-nft-1", "100000000cin", 0, MultisigInfo{"multiSig-delete-tx", "multisig-acc-nft-1", "", 0, nil, "nft-grp-addr-4", 0, internalTx2x_createToken1}, "MEMO : Delete MultiSig Tx", nil},
		{"multiSig", true, true, "[case-1.0] Delete MultiSig Tx - Error, due to Only group account owner can remove pending tx.", "multisig-acc-nft-2", "100000000cin", 0, MultisigInfo{"multiSig-delete-tx", "multisig-acc-nft-2", "", 0, nil, "nft-grp-addr-1", 0, internalTx2x_createToken1}, "MEMO : Delete MultiSig Tx", nil},
		{"multiSig", true, true, "[case-1.0] Delete MultiSig Tx - Error, due to 'Pending tx is not found' which ID : 1.				", "multisig-acc-nft-1", "100000000cin", 0, MultisigInfo{"multiSig-delete-tx", "multisig-acc-nft-1", "", 0, nil, "nft-grp-addr-1", 1, internalTx2x_createToken1}, "MEMO : Delete MultiSig Tx", nil},

		{"nonFungibleToken", false, false, "[case-1.0] APPROVE nonfungible token [TNFT-PUBLIC-FALSE-01] - Happy path - wait-5-seconds.", "nft-mostafa", "100000000cin", 0, NonFungibleTokenInfo{"approve", "10000000", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-01", "nft-grp-addr-1", "", "token metadata", "", "item-properties", "item-metadata", true, false, true, true, false, "nft-jeansoon", "0", "nft-carlo", "default", "", "2", "2", []string{"nft-jeansoon", "nft-carlo"}, "10"}, "APPROVE nonfungible token [TNFT-PUBLIC-FALSE-01] - Happy path", nil},

		//1.0.1 mintItem - freezeItem - unfreezeItem
		{"multiSig", false, false, "[case-1.0] Create MultiSig Tx for NFTs [Mint-item] - submit counter+ - Happy Path - wait-5-seconds.", "multisig-acc-nft-1", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-1", 1, internalTx2x_mintItem_freeze1}, "MEMO : xxxxx", nil}, // nx "sequence":
		//refer NFTs: 13. freeze & unfreeze
		{"nonFungibleToken", false, false, "[case-1.0] FREEZE nonfungible item [Item-PUBLIC-FALSE-99] - Happy path - wait-5-seconds.", "nft-mostafa", "100000000cin", 0, NonFungibleTokenInfo{"freeze-item", "10000000", "", "", "TNFT-PUBLIC-FALSE-01", "nft-mostafa", "", "token metadata", "Item-PUBLIC-FALSE-99", "", "", true, false, false, true, false, "nft-jeansoon", "0", "nft-carlo", "", "", "", "", []string{""}, "10"}, "", nil}, //ok
		{"nonFungibleToken", true, true, "[case-1.0] UNFREEZE nonfungible item [Item-PUBLIC-FALSE-99] - Invalid signer - wait-5-seconds.", "nft-jeansoon", "100000000cin", 0, NonFungibleTokenInfo{"unfreeze-item", "10000000", "", "", "TNFT-PUBLIC-FALSE-01", "nft-jeansoon", "", "token metadata", "Item-PUBLIC-FALSE-99", "", "", true, false, false, false, false, "nft-jeansoon", "0", "nft-carlo", "", "", "", "", []string{""}, "10"}, "", nil},
		{"nonFungibleToken", true, true, "[case-1.0] UNFREEZE nonfungible item [Item-PUBLIC-FALSE-99] - No such non fungible token - wait-5-seconds.", "nft-mostafa", "100000000cin", 0, NonFungibleTokenInfo{"unfreeze-item", "10000000", "", "", "TNFT-PUBLIC-FALSE-01-1122334455", "nft-mostafa", "", "token metadata", "Item-PUBLIC-FALSE-99", "", "", true, false, false, false, false, "nft-jeansoon", "0", "nft-carlo", "", "", "", "", []string{""}, "10"}, "", nil},
		{"nonFungibleToken", true, true, "[case-1.0] UNFREEZE nonfungible item [Item-PUBLIC-FALSE-99] - No such non fungible item to unfreeze - wait-5-seconds.", "nft-mostafa", "100000000cin", 0, NonFungibleTokenInfo{"unfreeze-item", "10000000", "", "", "TNFT-PUBLIC-FALSE-01", "nft-mostafa", "", "token metadata", "Item-PUBLIC-FALSE-99-abc1123", "", "", true, false, false, false, false, "nft-jeansoon", "0", "nft-carlo", "", "", "", "", []string{""}, "10"}, "", nil},
		{"nonFungibleToken", true, true, "[case-1.0] UNFREEZE nonfungible item [Item-PUBLIC-FALSE-99] - Not authorised to unfreeze token account - wait-5-seconds.", "nft-yk", "100000000cin", 0, NonFungibleTokenInfo{"unfreeze-item", "10000000", "", "", "TNFT-PUBLIC-FALSE-01", "nft-yk", "", "token metadata", "Item-PUBLIC-FALSE-99", "", "", true, false, false, false, false, "nft-jeansoon", "0", "nft-carlo", "", "", "", "", []string{""}, "10"}, "", nil},
		{"nonFungibleToken", false, false, "[case-1.0] UNFREEZE nonfungible item [Item-PUBLIC-FALSE-99] - Happy path - wait-5-seconds.", "nft-mostafa", "100000000cin", 0, NonFungibleTokenInfo{"unfreeze-item", "10000000", "", "", "TNFT-PUBLIC-FALSE-01", "nft-mostafa", "", "token metadata", "Item-PUBLIC-FALSE-99", "", "", true, false, false, true, false, "nft-jeansoon", "0", "nft-carlo", "", "", "", "", []string{""}, "10"}, "", nil},
		{"nonFungibleToken", true, true, "[case-1.0] Re-UNFREEZE nonfungible item [Item-PUBLIC-FALSE-99] - Error due to Token-item already unfrozen - wait-5-seconds.", "nft-mostafa", "100000000cin", 0, NonFungibleTokenInfo{"unfreeze-item", "10000000", "", "", "TNFT-PUBLIC-FALSE-01", "nft-mostafa", "", "token metadata", "Item-PUBLIC-FALSE-99", "", "", true, false, false, true, false, "nft-jeansoon", "0", "nft-carlo", "", "", "", "", []string{""}, "10"}, "", nil}, // [Re-action]

		//1.0.2 mintItem - endorseItem - transferItem - burnItem
		{"multiSig", false, false, "[case-1.0] Create MultiSig Tx for NFTs [Mint-item] - submit counter+ - Happy Path - wait-5-seconds.", "multisig-acc-nft-1", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-1", 2, internalTx2x_mintItem1}, "MEMO : xxxxx", nil}, // nx "sequence":
		{"nonFungibleToken", false, false, "[case-1.0] ENDORSE nonfungible item [Item-PUBLIC-FALSE-01] - Happy path - wait-5-seconds.", "nft-carlo", "100000000cin", 0, NonFungibleTokenInfo{"endorsement-item", "", "", "", "TNFT-PUBLIC-FALSE-01", "nft-carlo", "", "token metadata", "Item-PUBLIC-FALSE-01", "", "", true, false, true, true, false, "", "", "", "", "", "", "", []string{"nft-jeansoon", "nft-carlo"}, "10"}, "ENDORSE nonfungible item [Item-PUBLIC-FALSE-01] - Happy path", nil},
		{"nonFungibleToken", false, false, "[case-1.0] TRANSFER nonfungible token item [Item-PUBLIC-FALSE-01] - Happy path", "nft-mostafa", "100000000cin", 0, NonFungibleTokenInfo{"transfer-item", "", "", "", "TNFT-PUBLIC-FALSE-01", "nft-mostafa", "nft-grp-addr-1", "token metadata", "Item-PUBLIC-FALSE-01", "item-properties", "item-metadata", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "TRANSFER nonfungible token item [Item-PUBLIC-FALSE-01] - Happy path", nil},
		{"multiSig", false, false, "[case-1.0] Create MultiSig Tx for NFTs [Burn-item] - submit counter+ - Happy Path", "multisig-acc-nft-1", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-1", 3, internalTx2x_burnItem1}, "MEMO : xxxxx", nil}, // nx "sequence":

		//transferTokenOwnership - Verify - Accept
		{"multiSig", false, false, "[case-1.0] Create MultiSig Tx for NFTs [Transfer-token-ownership] - submit counter+ - Happy Path - wait-5-seconds.", "multisig-acc-nft-1", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-1", 4, internalTx2x_transferTokenOwnership1}, "MEMO : xxxxx", nil}, // nx "sequence":
		{"nonFungibleToken", false, false, "[case-1.0] VERIFY nonfungible token transfer ownership [TNFT-PUBLIC-FALSE-01] - Happy path - wait-5-seconds.", "nft-mostafa", "0cin", 0, NonFungibleTokenInfo{"verify-transfer-token-ownership", "", "", "", "TNFT-PUBLIC-FALSE-01", "nft-mostafa", "nft-grp-addr-1", "token metadata", "", "", "", true, false, true, true, false, "nft-jeansoon", "0", "nft-carlo", "", "APPROVE_TRANSFER_TOKEN_OWNERSHIP", "", "", []string{""}, "10"}, "VERIFY nonfungible token transfer ownership [TNFT-PUBLIC-FALSE-01] - Happy path", nil},

		//Need signed by : {"multisig-acc-nft-2", "multisig-acc-nft-3", "multisig-acc-nft-4"}, owner=="multisig-acc-nft-1"
		//Threshold == 2, under 'nft-grp-addr-3'
		{"multiSig", false, false, "[case-1.0] Create MultiSig Tx for NFTs [Accept-token-ownership] - submit counter+ - Happy Path", "multisig-acc-nft-2", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-3", 0, internalTx2x_acceptTokenOwnership1}, "MEMO : xxxxx", nil}, // nx "sequence":
		{"multiSig", false, false, "[case-1.0] Sign MultiSig Tx for NFTs [Accept-token-ownership] - submit which signed by multisig-acc-nft-4", "multisig-acc-nft-4", "100000000cin", 0, MultisigInfo{"multiSig-sign-tx", "", "", 0, nil, "nft-grp-addr-3", 0, internalTx2x_acceptTokenOwnership1}, "MEMO : Sign MultiSig Tx", nil},

		//Multisig Process : Multisig-transfer-ownership
		{"multiSig", true, true, "[case-1.0] Transfer MultiSig Owner - Error, due to Group address invalid.                                                                ", "multisig-acc-nft-1", "800400000cin", 0, MultisigInfo{"transfer-ownership", "multisig-acc-nft-1", "multisig-acc-nft-2", 0, nil, "nft-grp-addr-5", 0, nil}, "MEMO : Transfer MultiSig Owner.", nil},
		{"multiSig", true, true, "[case-1.0] Transfer MultiSig Owner - Error, due to Owner of group address invalid.                                                       ", "multisig-acc-nft-3", "800400000cin", 0, MultisigInfo{"transfer-ownership", "multisig-acc-nft-3", "multisig-acc-nft-1", 0, nil, "nft-grp-addr-1", 0, nil}, "MEMO : Transfer MultiSig Owner.", nil},
		{"multiSig", true, true, "[case-1.0] Transfer MultiSig Owner - Error, due to without KYC.                                                                          ", "multisig-nokyc", "800400000cin", 0, MultisigInfo{"transfer-ownership", "multisig-acc-nft-1", "multisig-nokyc", 0, nil, "nft-grp-addr-1", 0, nil}, "MEMO : Transfer MultiSig Owner.", nil},
		{"multiSig", false, false, "[case-1.0] Transfer MultiSig Owner - [from multisig-acc-nft-1 to multisig-acc-nft-2] - Happy Path                                   						", "multisig-acc-nft-1", "800400000cin", 0, MultisigInfo{"transfer-ownership", "multisig-acc-nft-1", "multisig-acc-nft-2", 0, nil, "nft-grp-addr-1", 0, nil}, "MEMO : Transfer MultiSig Owner.", nil},
		{"multiSig", true, true, "[case-1.0] Re-transfer MultiSig Owner - Error, due to Owner of group address invalid as MultiSig-account already been transfer to others.", "multisig-acc-nft-1", "800400000cin", 0, MultisigInfo{"transfer-ownership", "multisig-acc-nft-1", "multisig-acc-nft-2", 0, nil, "nft-grp-addr-1", 0, nil}, "MEMO : Transfer MultiSig Owner.", nil},

		//refer NFTs: 10. freeze
		{"nonFungibleToken", false, false, "[case-1.0] FREEZE nonfungible token - Happy path. commit", "nft-mostafa", "0cin", 0, NonFungibleTokenInfo{"freeze", "", "", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-01", "", "", "token metadata", "", "", "", true, false, false, true, false, "nft-jeansoon", "0", "nft-carlo", "", "", "", "", []string{""}, "10"}, "MEMO: [case-1.0] FREEZE nonfungible token - Happy path. commit", nil},
		{"nonFungibleToken", true, true, "[case-1.0] FREEZE nonfungible token - Not authorised to approve due to Invalid Fee collector", "nft-mostafa", "100000000cin", 0, NonFungibleTokenInfo{"freeze", "10000000", "nft-yk", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-01", "", "", "token metadata", "", "", "", true, false, false, false, false, "nft-jeansoon", "0", "nft-carlo", "", "", "", "", []string{""}, "10"}, "MEMO: [case-1.0] FREEZE nonfungible token - Not authorised to approve due to Invalid Fee collector", nil},
		{"nonFungibleToken", true, true, "[case-1.0] FREEZE nonfungible token - Invalid Token symbol", "nft-mostafa", "100000000cin", 0, NonFungibleTokenInfo{"freeze", "10000000", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-01---abc333", "", "", "token metadata", "", "", "", true, false, false, false, false, "nft-jeansoon", "0", "nft-carlo", "", "", "", "", []string{""}, "10"}, "MEMO: [case-1.0] FREEZE nonfungible token - Invalid Token symbol", nil},
		{"nonFungibleToken", true, true, "[case-1.0] Re-FREEZE nonfungible token - Error due to Token is frozen.", "nft-mostafa", "0cin", 0, NonFungibleTokenInfo{"freeze", "", "", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-01", "", "", "token metadata", "", "", "", true, false, false, true, false, "nft-jeansoon", "0", "nft-carlo", "", "", "", "", []string{""}, "10"}, "MEMO: [case-1.0] Re-FREEZE nonfungible token - Error due to Token is frozen.", nil}, // [Re-action]

		//refer NFTs: 11. unfreeze
		{"nonFungibleToken", false, false, "[case-1.0] UNFREEZE nonfungible token - Happy path", "nft-mostafa", "0cin", 0, NonFungibleTokenInfo{"unfreeze", "", "", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-01", "", "", "token metadata", "", "", "", true, false, false, true, false, "nft-jeansoon", "0", "nft-carlo", "", "", "", "", []string{""}, "10"}, "MEMO: case-1.0] UNFREEZE nonfungible token - Happy path", nil},
		{"nonFungibleToken", true, true, "[case-1.0] UNFREEZE nonfungible token - Not authorised to approve due to Invalid Fee collector", "nft-mostafa", "100000000cin", 0, NonFungibleTokenInfo{"unfreeze", "10000000", "nft-yk", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-01", "", "", "token metadata", "", "", "", true, false, false, false, false, "nft-jeansoon", "0", "nft-carlo", "", "", "", "", []string{""}, "10"}, "MEMO: [case-1.0] UNFREEZE nonfungible token - Not authorised to approve due to Invalid Fee collector", nil},
		{"nonFungibleToken", true, true, "[case-1.0] UNFREEZE nonfungible token - Invalid Token symbol", "nft-mostafa", "100000000cin", 0, NonFungibleTokenInfo{"unfreeze", "10000000", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-01---abc711", "", "", "token metadata", "", "", "", true, false, false, false, false, "nft-jeansoon", "0", "nft-carlo", "", "", "", "", []string{""}, "10"}, "MEMO: [case-1.0] UNFREEZE nonfungible token - Invalid Token symbol", nil},
		{"nonFungibleToken", true, true, "[case-1.0] Re-UNFREEZE nonfungible token - Error due to token already unfreeze.", "nft-mostafa", "0cin", 0, NonFungibleTokenInfo{"unfreeze", "", "", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-01", "", "", "token metadata", "", "", "", true, false, false, true, false, "nft-jeansoon", "0", "nft-carlo", "", "", "", "", []string{""}, "10"}, "MEMO: [case-1.0] Re-UNFREEZE nonfungible token - Error due to token already unfreeze.", nil}, //[Re-action]

		// ============================================case-2.0 :  with TWO signers - with InternalTx Error-cases
		//create-token
		{"multiSig", false, false, "[case-2.0] Create MultiSig Tx for NFTs [Create-token] - submit - Happy Path - wait-5-seconds.", "multisig-acc-nft-2", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-2", 0, internalTx3x_createToken1}, "MEMO : Create MultiSig Tx", nil},

		//Multisig Process : delete tx - before start 'Sign MultiSig Tx'
		{"multiSig", true, true, "[case-2.0] Delete MultiSig Tx - Error, due to Group address invalid. 													", "multisig-acc-nft-1", "100000000cin", 0, MultisigInfo{"multiSig-delete-tx", "multisig-acc-nft-1", "", 0, nil, "nft-grp-addr-4", 0, internalTx3x_createToken1}, "MEMO : Delete MultiSig Tx", nil},
		{"multiSig", true, true, "[case-2.0] Delete MultiSig Tx - Error, due to Only group account owner can remove pending tx. ", "multisig-acc-nft-2", "100000000cin", 0, MultisigInfo{"multiSig-delete-tx", "multisig-acc-nft-2", "", 0, nil, "nft-grp-addr-2", 0, internalTx3x_createToken1}, "MEMO : Delete MultiSig Tx", nil},
		{"multiSig", true, true, "[case-2.0] Delete MultiSig Tx - Error, due to 'Pending tx is not found' which ID : 1. 				", "multisig-acc-nft-1", "100000000cin", 0, MultisigInfo{"multiSig-delete-tx", "multisig-acc-nft-1", "", 0, nil, "nft-grp-addr-2", 1, internalTx3x_createToken1}, "MEMO : Delete MultiSig Tx", nil},

		{"multiSig", false, false, "[case-2.0] Sign MultiSig Tx for NFTs [Create-token] - submit which signed by multisig-acc-nft-3 - wait-5-seconds.", "multisig-acc-nft-3", "100000000cin", 0, MultisigInfo{"multiSig-sign-tx", "", "", 0, nil, "nft-grp-addr-2", 0, internalTx3x_createToken1}, "MEMO : Sign MultiSig Tx", nil},
		{"nonFungibleToken", false, false, "[case-2.0] APPROVE nonfungible token [TNFT-PUBLIC-FALSE-02] - Happy path - wait-5-seconds.", "nft-mostafa", "100000000cin", 0, NonFungibleTokenInfo{"approve", "10000000", "nft-mostafa", "TestNonFungibleToken", "TNFT-PUBLIC-FALSE-02", "nft-grp-addr-2", "", "token metadata", "", "item-properties", "item-metadata", true, false, true, true, false, "nft-jeansoon", "0", "nft-carlo", "default", "", "2", "2", []string{"nft-jeansoon", "nft-carlo"}, "10"}, "[case-2.0] APPROVE nonfungible token [TNFT-PUBLIC-FALSE-02] - Happy path", nil},

		//Refer : Update-Token-Metadata (is multisig)
		{"multiSig", false, false, "[case-2.0] Create MultiSig Tx for NFTs [Update-nft-metadata] - submit counter+ - Happy Path - wait-5-seconds.", "multisig-acc-nft-2", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-2", 1, internalTx3x_updateNFTMetadata1}, "MEMO : xxxxx", nil}, // nx "sequence":
		{"multiSig", true, true, "[case-2.0] Create MultiSig Tx for NFTs [Update-nft-metadata] - [internalTx3x_updateNFTMetadata_err1].", "multisig-acc-nft-2", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-2", 2, internalTx3x_updateNFTMetadata_err1}, "MEMO : xxxxx", nil},       // Remarks : Due to (true, true), this txID not impact next case of txID
		{"multiSig", false, false, "[case-2.0] Create MultiSig Tx for NFTs [Update-nft-metadata] - [internalTx3x_updateNFTMetadata_err3].", "multisig-acc-nft-2", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-2", 2, internalTx3x_updateNFTMetadata_err3}, "MEMO : xxxxx", nil},     // nx "sequence":
		{"multiSig", false, false, "[case-2.0] Sign MultiSig Tx for NFTs [Update-nft-metadata] - submit which signed by multisig-acc-nft-3 - wait-5-seconds.", "multisig-acc-nft-3", "100000000cin", 0, MultisigInfo{"multiSig-sign-tx", "", "", 0, nil, "nft-grp-addr-2", 1, internalTx3x_updateNFTMetadata1}, "MEMO : Sign MultiSig Tx", nil},
		{"multiSig", false, false, "[case-2.0] Create MultiSig Tx for NFTs [Update-nft-metadata] - Re-submit counter+ - Happy Path - wait-5-seconds.", "multisig-acc-nft-2", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-2", 3, internalTx3x_updateNFTMetadata_Reupdate1}, "MEMO : xxxxx", nil}, // nx "sequence":
		{"multiSig", false, false, "[case-2.0] Sign MultiSig Tx for NFTs [Update-nft-metadata] - Re-submit which signed by multisig-acc-nft-3 - wait-5-seconds.", "multisig-acc-nft-3", "100000000cin", 0, MultisigInfo{"multiSig-sign-tx", "", "", 0, nil, "nft-grp-addr-2", 3, internalTx3x_updateNFTMetadata_Reupdate1}, "MEMO : Sign MultiSig Tx", nil},

		//mintItem - endorseItem - transferItem - burnItem
		{"multiSig", false, false, "[case-2.0] Create MultiSig Tx for NFTs [Mint-item] - submit counter+ - Happy Path - wait-5-seconds.", "multisig-acc-nft-2", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-2", 4, internalTx3x_mintItem1}, "MEMO : xxxxx", nil}, // nx "sequence":
		{"multiSig", false, false, "[case-2.0] Create MultiSig Tx for NFTs [Mint-item] - [internalTx3x_mintItem_err1]", "multisig-acc-nft-2", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-2", 5, internalTx3x_mintItem_err1}, "MEMO : xxxxx", nil},               // nx "sequence":
		{"multiSig", false, false, "[case-2.0] Create MultiSig Tx for NFTs [Mint-item] - [internalTx3x_mintItem_err3]", "multisig-acc-nft-2", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-2", 6, internalTx3x_mintItem_err3}, "MEMO : xxxxx", nil},               // nx "sequence":
		{"multiSig", false, false, "[case-2.0] Sign MultiSig Tx for NFTs [Mint-item] - submit which signed by multisig-acc-nft-3 - wait-5-seconds.", "multisig-acc-nft-3", "100000000cin", 0, MultisigInfo{"multiSig-sign-tx", "", "", 0, nil, "nft-grp-addr-2", 4, internalTx3x_mintItem1}, "MEMO : Sign MultiSig Tx", nil},
		{"multiSig", false, false, "[case-2.0] Create MultiSig Tx for NFTs [Re-Mint-item] - OK PASS due to MINT limit not exceed. - wait-5-seconds.", "multisig-acc-nft-2", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-2", 7, internalTx3x_mintItem_Remint1}, "MEMO : [case-2.0] Create MultiSig Tx for NFTs [Re-Mint-item] - OK PASS due to MINT limit not exceed.", nil},                                                                 //Re-action
		{"multiSig", false, false, "[case-2.0] Sign MultiSig Tx for NFTs [Re-Mint-item] - OK PASS due to MINT limit not exceed, which signed by multisig-acc-nft-3 - wait-5-seconds.", "multisig-acc-nft-3", "100000000cin", 0, MultisigInfo{"multiSig-sign-tx", "", "", 0, nil, "nft-grp-addr-2", 7, internalTx3x_mintItem_Remint1}, "MEMO : [case-2.0] Sign MultiSig Tx for NFTs [Re-Mint-item] - OK PASS due to MINT limit not exceed, which signed by multisig-acc-nft-3", nil}, //Re-action
		{"multiSig", false, false, "[case-2.0] Create MultiSig Tx for NFTs [Re-Mint-item] - Error due to MINT limit exceeded. - wait-5-seconds.", "multisig-acc-nft-2", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-2", 8, internalTx3x_mintItem_err4}, "MEMO : [case-2.0] Create MultiSig Tx for NFTs [Re-Mint-item] - Error due to MINT limit exceeded.", nil},                                                                            //Re-action
		{"multiSig", false, false, "[case-2.0] Sign MultiSig Tx for NFTs [Re-Mint-item] - Error due to MINT limit exceeded, which signed by multisig-acc-nft-3 - wait-5-seconds.", "multisig-acc-nft-3", "100000000cin", 0, MultisigInfo{"multiSig-sign-tx", "", "", 0, nil, "nft-grp-addr-2", 8, internalTx3x_mintItem_err4}, "MEMO : [case-2.0] Sign MultiSig Tx for NFTs [Re-Mint-item] - Error due to MINT limit exceeded, which signed by multisig-acc-nft-3", nil},            //Re-action

		//Refer : Update-Item-Metadata (non-multisig)
		{"nonFungibleToken", true, true, "[case-2.0] UPDATE ITEM METADATA nonfungible token item (Modifiable==TRUE) - Error due to metadata field length problem which is very long!.", "nft-mostafa", "100000000cin", 0, NonFungibleTokenInfo{"update-item-metadata", "", "", "", "TNFT-PUBLIC-FALSE-02", "nft-mostafa", "", "token metadata", "Item-PUBLIC-FALSE-02", "item-properties", "updated item-metadata : aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAA------aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaBBBBBB----aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaCCCCCC------aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAA-DDDDDD------aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAA-PPPPPP------aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAA-QQQQQQ------aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAA-RRRRRR------aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAA-SSSSSS", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: [case-2.0] UPDATE ITEM METADATA nonfungible token item (Modifiable==TRUE) - Error due to metadata field length problem which is very long!", nil},
		{"nonFungibleToken", true, true, "[case-2.0] UPDATE ITEM METADATA nonfungible token item (Modifiable==TRUE) - Error due to using Token-owner.", "multisig-acc-nft-2", "100000000cin", 0, NonFungibleTokenInfo{"update-item-metadata", "", "", "", "TNFT-PUBLIC-FALSE-02", "nft-grp-addr-2", "", "token metadata", "Item-PUBLIC-FALSE-02", "item-properties", "item-metadata", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: [case-2.0] UPDATE ITEM METADATA nonfungible token item (Modifiable==TRUE) - Error due to using Token-owner.", nil},
		{"nonFungibleToken", true, true, "[case-2.0] UPDATE ITEM METADATA nonfungible token item (Modifiable==TRUE) - Error due to Item owner not match.", "nft-yk", "100000000cin", 0, NonFungibleTokenInfo{"update-item-metadata", "", "", "", "TNFT-PUBLIC-FALSE-02", "nft-yk", "", "token metadata", "Item-PUBLIC-FALSE-02", "item-properties", "item-metadata", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: [case-2.0] UPDATE ITEM METADATA nonfungible token item (Modifiable==TRUE) - Error due to Item owner not match.", nil},
		{"nonFungibleToken", false, false, "[case-2.0] UPDATE ITEM METADATA nonfungible token item (Modifiable==TRUE) - Happy Path using Item-owner.  commit", "nft-mostafa", "100000000cin", 0, NonFungibleTokenInfo{"update-item-metadata", "", "", "", "TNFT-PUBLIC-FALSE-02", "nft-mostafa", "", "token metadata", "Item-PUBLIC-FALSE-02", "item-properties", "item-metadata", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: [case-2.0] UPDATE ITEM METADATA nonfungible token item (Modifiable==TRUE) - Happy Path using Item-owner.  commit", nil},
		{"nonFungibleToken", false, false, "[case-2.0] Re-UPDATE ITEM METADATA nonfungible token item (Modifiable==TRUE) - Happy Path using Item-owner.  commit", "nft-mostafa", "100000000cin", 0, NonFungibleTokenInfo{"update-item-metadata", "", "", "", "TNFT-PUBLIC-FALSE-02", "nft-mostafa", "", "token metadata", "Item-PUBLIC-FALSE-02", "item-properties", "item-metadata", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "MEMO: Re-UPDATE ITEM METADATA nonfungible token item again here, in order to test the ability of it", nil}, // Re-action

		{"nonFungibleToken", false, false, "[case-2.0] ENDORSE nonfungible item [Item-PUBLIC-FALSE-02] - Happy path - wait-5-seconds.", "nft-carlo", "100000000cin", 0, NonFungibleTokenInfo{"endorsement-item", "", "", "", "TNFT-PUBLIC-FALSE-02", "nft-carlo", "", "token metadata", "Item-PUBLIC-FALSE-02", "", "", true, false, true, true, false, "", "", "", "", "", "", "", []string{"nft-jeansoon", "nft-carlo"}, "10"}, "[case-2.0] ENDORSE nonfungible item [Item-PUBLIC-FALSE-02] - Happy path", nil},
		{"nonFungibleToken", false, false, "[case-2.0] TRANSFER nonfungible token item [Item-PUBLIC-FALSE-02] - Happy path", "nft-mostafa", "100000000cin", 0, NonFungibleTokenInfo{"transfer-item", "", "", "", "TNFT-PUBLIC-FALSE-02", "nft-mostafa", "nft-yk", "token metadata", "Item-PUBLIC-FALSE-02", "item-properties", "item-metadata", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "[case-2.0] TRANSFER nonfungible token item [Item-PUBLIC-FALSE-02] - Happy path", nil},
		{"nonFungibleToken", false, false, "[case-2.0] Re-TRANSFER nonfungible token item [Item-PUBLIC-FALSE-02] - Re-transfer Item Happy path", "nft-yk", "100000000cin", 0, NonFungibleTokenInfo{"transfer-item", "", "", "", "TNFT-PUBLIC-FALSE-02", "nft-yk", "nft-grp-addr-2", "token metadata", "Item-PUBLIC-FALSE-02", "item-properties", "item-metadata", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "[case-2.0] Re-TRANSFER nonfungible token item [Item-PUBLIC-FALSE-02] - Re-transfer Item Happy path", nil},                   //Re-action
		{"nonFungibleToken", true, true, "[case-2.0] Re-TRANSFER nonfungible token item [Item-PUBLIC-FALSE-02] - Error due to Transfer limit exceeded.", "nft-yk", "100000000cin", 0, NonFungibleTokenInfo{"transfer-item", "", "", "", "TNFT-PUBLIC-FALSE-02", "nft-yk", "nft-grp-addr-2", "token metadata", "Item-PUBLIC-FALSE-02", "item-properties", "item-metadata", true, false, true, true, false, "", "", "", "", "", "", "", []string{""}, "10"}, "[case-2.0] Re-TRANSFER nonfungible token item [Item-PUBLIC-FALSE-02] - Error due to Transfer limit exceeded.", nil}, //Re-action

		{"multiSig", false, false, "[case-2.0] Create MultiSig Tx for NFTs [Burn-item] - submit counter+ - Happy Path.", "multisig-acc-nft-2", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-2", 9, internalTx3x_burnItem1}, "MEMO : xxxxx", nil},      // nx "sequence":
		{"multiSig", false, false, "[case-2.0] Create MultiSig Tx for NFTs [Burn-item] - [internalTx3x_burnItem_err1].", "multisig-acc-nft-2", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-2", 10, internalTx3x_burnItem_err1}, "MEMO : xxxxx", nil}, // nx "sequence":
		{"multiSig", false, false, "[case-2.0] Create MultiSig Tx for NFTs [Burn-item] - [internalTx3x_burnItem_err3].", "multisig-acc-nft-2", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-2", 11, internalTx3x_burnItem_err3}, "MEMO : xxxxx", nil}, // nx "sequence":
		{"multiSig", false, false, "[case-2.0] Sign MultiSig Tx for NFTs [Burn-item] - submit which signed by multisig-acc-nft-3.", "multisig-acc-nft-3", "100000000cin", 0, MultisigInfo{"multiSig-sign-tx", "", "", 0, nil, "nft-grp-addr-2", 9, internalTx3x_burnItem1}, "MEMO : Sign MultiSig Tx", nil},

		//transferTokenOwnership - Verify - Accept
		{"multiSig", false, false, "[case-2.0] Create MultiSig Tx for NFTs [Transfer-token-ownership] - submit counter+ - Happy Path - wait-5-seconds.", "multisig-acc-nft-2", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-2", 12, internalTx3x_transferTokenOwnership1}, "MEMO : xxxxx", nil},  // nx "sequence":
		{"multiSig", false, false, "[case-2.0] Create MultiSig Tx for NFTs [Transfer-token-ownership] - [internalTx3x_transferTokenOwnership_err1].", "multisig-acc-nft-2", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-2", 13, internalTx3x_transferTokenOwnership_err1}, "MEMO : xxxxx", nil}, // nx "sequence":
		{"multiSig", false, false, "[case-2.0] Create MultiSig Tx for NFTs [Transfer-token-ownership] - [internalTx3x_transferTokenOwnership_err3].", "multisig-acc-nft-2", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-2", 14, internalTx3x_transferTokenOwnership_err3}, "MEMO : xxxxx", nil}, // nx "sequence":
		{"multiSig", false, false, "[case-2.0] Sign MultiSig Tx for NFTs [Transfer-token-ownership] - submit which signed by multisig-acc-nft-3 - wait-5-seconds.", "multisig-acc-nft-3", "100000000cin", 0, MultisigInfo{"multiSig-sign-tx", "", "", 0, nil, "nft-grp-addr-2", 12, internalTx3x_transferTokenOwnership1}, "MEMO : Sign MultiSig Tx", nil},
		{"nonFungibleToken", false, false, "[case-2.0] VERIFY nonfungible token transfer ownership [TNFT-PUBLIC-FALSE-02] - Happy path - wait-5-seconds.", "nft-mostafa", "0cin", 0, NonFungibleTokenInfo{"verify-transfer-token-ownership", "", "", "", "TNFT-PUBLIC-FALSE-02", "nft-mostafa", "nft-grp-addr-2", "token metadata", "", "", "", true, false, true, true, false, "nft-jeansoon", "0", "nft-carlo", "", "APPROVE_TRANSFER_TOKEN_OWNERSHIP", "", "", []string{""}, "10"}, "[case-2.0] VERIFY nonfungible token transfer ownership [TNFT-PUBLIC-FALSE-02] - Happy path", nil},

		// Need signed by : {"multisig-acc-nft-2", "multisig-acc-nft-3", "multisig-acc-nft-4"}, owner=="multisig-acc-nft-1"
		// Threshold == 3, under 'nft-grp-addr-4'
		{"multiSig", false, false, "[case-2.0] Create MultiSig Tx for NFTs [Accept-token-ownership] - submit counter+ - Happy Path.", "multisig-acc-nft-2", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-4", 0, internalTx3x_acceptTokenOwnership1}, "MEMO : xxxxx", nil},                 // nx "sequence":
		{"multiSig", false, false, "[case-2.0] Create MultiSig Tx for NFTs [Accept-token-ownership] - [internalTx3x_acceptTokenOwnership_err1].", "multisig-acc-nft-4", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-4", 1, internalTx3x_acceptTokenOwnership_err1}, "MEMO : xxxxx", nil}, // nx "sequence":
		{"multiSig", false, false, "[case-2.0] Create MultiSig Tx for NFTs [Accept-token-ownership] - [internalTx3x_acceptTokenOwnership_err3].", "multisig-acc-nft-4", "100000000cin", 0, MultisigInfo{"create-internal-tx", "", "", 0, nil, "nft-grp-addr-4", 2, internalTx3x_acceptTokenOwnership_err3}, "MEMO : xxxxx", nil}, // nx "sequence":
		{"multiSig", false, false, "[case-2.0] Sign MultiSig Tx for NFTs [Accept-token-ownership] - submit which signed by multisig-acc-nft-4.", "multisig-acc-nft-4", "100000000cin", 0, MultisigInfo{"multiSig-sign-tx", "", "", 0, nil, "nft-grp-addr-4", 0, internalTx3x_acceptTokenOwnership1}, "MEMO : Sign MultiSig Tx", nil},
		{"multiSig", false, false, "[case-2.0] Sign MultiSig Tx for NFTs [Accept-token-ownership] - submit which signed by multisig-acc-nft-3.", "multisig-acc-nft-3", "100000000cin", 0, MultisigInfo{"multiSig-sign-tx", "", "", 0, nil, "nft-grp-addr-4", 0, internalTx3x_acceptTokenOwnership1}, "MEMO : Sign MultiSig Tx", nil},

		//Multisig Process : Multisig-transfer-ownership
		{"multiSig", true, true, "[case-2.0] Transfer MultiSig Owner - Error, due to Group address invalid.																															 ", "multisig-acc-nft-1", "100000000cin", 0, MultisigInfo{"transfer-ownership", "multisig-acc-nft-1", "multisig-acc-nft-4", 0, nil, "nft-grp-addr-5", 0, nil}, "MEMO : Transfer MultiSig Owner.", nil},
		{"multiSig", true, true, "[case-2.0] Transfer MultiSig Owner - Error, due to Owner of group address invalid.																											 ", "multisig-acc-nft-2", "100000000cin", 0, MultisigInfo{"transfer-ownership", "multisig-acc-nft-2", "multisig-acc-nft-4", 0, nil, "nft-grp-addr-2", 0, nil}, "MEMO : Transfer MultiSig Owner.", nil},
		{"multiSig", true, true, "[case-2.0] Transfer MultiSig Owner - Error, due to without KYC.																																					 ", "multisig-nokyc", "100000000cin", 0, MultisigInfo{"transfer-ownership", "multisig-acc-nft-1", "multisig-nokyc", 0, nil, "nft-grp-addr-2", 0, nil}, "MEMO : Transfer MultiSig Owner.", nil},
		{"multiSig", false, false, "[case-2.0] Transfer MultiSig Owner - [from multisig-acc-nft-1 to multisig-acc-nft-4] Happy Path.																		 ", "multisig-acc-nft-1", "100000000cin", 0, MultisigInfo{"transfer-ownership", "multisig-acc-nft-1", "multisig-acc-nft-4", 0, nil, "nft-grp-addr-2", 0, nil}, "MEMO : Transfer MultiSig Owner.", nil},
		{"multiSig", true, true, "[case-2.0] Re-transfer MultiSig Owner - Error, due to Owner of group address invalid [MultiSig-account already been transfer to others].", "multisig-acc-nft-1", "100000000cin", 0, MultisigInfo{"transfer-ownership", "multisig-acc-nft-1", "multisig-acc-nft-4", 0, nil, "nft-grp-addr-2", 0, nil}, "MEMO : Transfer MultiSig Owner.", nil},

		// signer without through KYC
		{"multiSig", true, true, "Create MultiSig Account for NFTs using nonkyc as signer - Error, due to without KYC            ", "multisig-nokyc", "800400000cin", 0, MultisigInfo{"create", "multisig-nokyc", "", 2, []string{"multisig-acc-nft-1", "multisig-nokyc"}, "", 0, nil}, "", nil},
	}

	return tcs
}
